// Code generated by client-gen. DO NOT EDIT.

package agentgateway

import (
	context "context"

	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	scheme "github.com/agentgateway/agentgateway/controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentgatewayModelsGetter has a method to return a AgentgatewayModelInterface.
// A group's client should implement this interface.
type AgentgatewayModelsGetter interface {
	AgentgatewayModels(namespace string) AgentgatewayModelInterface
}

// AgentgatewayModelInterface has methods to work with AgentgatewayModel resources.
type AgentgatewayModelInterface interface {
	Create(ctx context.Context, agentgatewayModel *v1alpha1agentgateway.AgentgatewayModel, opts v1.CreateOptions) (*v1alpha1agentgateway.AgentgatewayModel, error)
	Update(ctx context.Context, agentgatewayModel *v1alpha1agentgateway.AgentgatewayModel, opts v1.UpdateOptions) (*v1alpha1agentgateway.AgentgatewayModel, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agentgatewayModel *v1alpha1agentgateway.AgentgatewayModel, opts v1.UpdateOptions) (*v1alpha1agentgateway.AgentgatewayModel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1agentgateway.AgentgatewayModel, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1agentgateway.AgentgatewayModelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1agentgateway.AgentgatewayModel, err error)
	AgentgatewayModelExpansion
}

// agentgatewayModels implements AgentgatewayModelInterface
type agentgatewayModels struct {
	*gentype.ClientWithList[*v1alpha1agentgateway.AgentgatewayModel, *v1alpha1agentgateway.AgentgatewayModelList]
}

// newAgentgatewayModels returns a AgentgatewayModels
func newAgentgatewayModels(c *AgentgatewayAgentgatewayClient, namespace string) *agentgatewayModels {
	return &agentgatewayModels{
		gentype.NewClientWithList[*v1alpha1agentgateway.AgentgatewayModel, *v1alpha1agentgateway.AgentgatewayModelList](
			"agentgatewaymodels",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1agentgateway.AgentgatewayModel { return &v1alpha1agentgateway.AgentgatewayModel{} },
			func() *v1alpha1agentgateway.AgentgatewayModelList {
				return &v1alpha1agentgateway.AgentgatewayModelList{}
			},
		),
	}
}
