binds:
- port: 8080
  listeners:
  - name: http
    protocol: HTTP
    routes:
    - backends:
      - host: datadog.example.com:443
        policies:
          backendAuth:
            credentials:
              - location:
                  header:
                    name: dd-api-key
                key: primary-api-key
              - location:
                  header:
                    name: dd-application-key
                key: application-key
              - location:
                  header:
                    name: x-auth-token
                    prefix: "Bearer "
                key: token-value
    - backends:
      - host: combined.example.com:443
        policies:
          backendAuth:
            key:
              value: primary-creds
            credentials:
              - location:
                  header:
                    name: x-auth-email
                key: user@example.com
