// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	agentgateway "github.com/agentgateway/agentgateway/controller/api/v1alpha1/agentgateway"
	v1alpha1agentgateway "github.com/agentgateway/agentgateway/controller/pkg/client/clientset/versioned/typed/v1alpha1/agentgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgentgatewayModels implements AgentgatewayModelInterface
type fakeAgentgatewayModels struct {
	*gentype.FakeClientWithList[*agentgateway.AgentgatewayModel, *agentgateway.AgentgatewayModelList]
	Fake *FakeAgentgatewayAgentgateway
}

func newFakeAgentgatewayModels(fake *FakeAgentgatewayAgentgateway, namespace string) v1alpha1agentgateway.AgentgatewayModelInterface {
	return &fakeAgentgatewayModels{
		gentype.NewFakeClientWithList[*agentgateway.AgentgatewayModel, *agentgateway.AgentgatewayModelList](
			fake.Fake,
			namespace,
			agentgateway.SchemeGroupVersion.WithResource("agentgatewaymodels"),
			agentgateway.SchemeGroupVersion.WithKind("AgentgatewayModel"),
			func() *agentgateway.AgentgatewayModel { return &agentgateway.AgentgatewayModel{} },
			func() *agentgateway.AgentgatewayModelList { return &agentgateway.AgentgatewayModelList{} },
			func(dst, src *agentgateway.AgentgatewayModelList) { dst.ListMeta = src.ListMeta },
			func(list *agentgateway.AgentgatewayModelList) []*agentgateway.AgentgatewayModel {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *agentgateway.AgentgatewayModelList, items []*agentgateway.AgentgatewayModel) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
