name: Branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            # Performance is horrendous on musl without jemalloc
            features: jemalloc
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-musl
            # Performance is horrendous on musl without jemalloc
            # TODO: arm64 build fails with jemalloc for some reason?
            features: default
          - os: macos-latest
            target: aarch64-apple-darwin
            features: default
          - os: windows-2025
            target: x86_64-pc-windows-msvc
            features: default

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 23
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build UI
      run: | 
        cd ui
        npm install
        npm run build
    - name: Install musl-tools
      if: ${{ matrix.os == 'ubuntu-22.04-arm' || matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools
        rustup target add ${{ matrix.target }}
    - name: Build
      run: make build
      env:
        CARGO_BUILD_ARGS: "--target ${{ matrix.target }} -F ${{ matrix.features }}"

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install jq on Windows
      if: runner.os == 'Windows'
      run: choco install jq -y
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Add Go bin to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - name: Test
      run: make test
    - name: Validate
      run: make validate
    - name: Generation
      run: make gen check-clean-repo
    - name: Lint
      run: make lint

  docker:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      env:
        DOCKER_BUILDER: "docker buildx"
        DOCKER_BUILD_ARGS: "--cache-from type=registry,ref=ghcr.io/agentgateway/agentgateway:buildcache"
      run: make docker
